### ISSUE TITLE
Difference between input and output

### ISSUE THREAD

**Issue by sandsmark** [apocalyptech/bl3-cli-saveedit#1]
Just reading and writing a savegame (`python -m bl3save.cli_edit 1.sav test.sav`) seems to change the size of it for some reason (increasing it by 620 bytes). According to dhex the first changed bytes seem to be the size of the data field in the header (adding 620 there), and then at 0x4262 it seems to start diverging a lot.

Any idea why? I assume it doesn't break anything, but still interesting.

**Comment by apocalyptech** [comment]
Howdy!  Yeah, I'd mentioned that in the README (though I'm sure it's easy to miss among all that block of text) -- I think it's just down to how Google's Python protobuf library differs from whatever library they're using at GBX.  I'd noticed that right away when I first started using the thing, but I've yet to find any problems with the resulting files, so I've been assuming it's just an encoding difference in the libraries.  The old BL2 CLI utilities do the same, as does Gibbed's BL2/TPS editors, so I admit I've not really looked into it too closely.  Could be that the game just does various size optimizations to cut down on file size or something.

If you do find something solid, let me know, of course!  Not sure it's really worth looking into, though.  :)

**Comment by sandsmark** [comment]
Well, I just got curious (and just in case there's something subtly wrong). :-)

Unless I'm calculating offsets wrong looking at the raw protobuf dumps (the raw dumps from both the original and rewritten are identical fwiw, which points to the protobufs being off) it seems to start diverging right after the equipment slots:
![image](https://user-images.githubusercontent.com/25765/79006806-74c33280-7b49-11ea-88c3-4d592c234d16.png)

**Comment by apocalyptech** [comment]
As I mentioned on the PR, your stuff's merged in now, even if I didn't really do it properly PRwise.  Thanks again!  Nice to have this thing have a 1:1 data relation.  :)
