### ISSUE TITLE
Add a way to edit Golden Keys

### ISSUE THREAD

**Issue by mightydanp** [apocalyptech/bl3-cli-saveedit#10]
Add a way to edit Golden Keys

**Comment by apocalyptech** [comment]
I'd actually looked for that out of curiosity but couldn't find anything that looked like a golden key count in there.  Did you want to export the JSON on your own profile and see if you can find anything in there?  At the moment I'm thinking that the game might always just get that info from SHiFT.

**Comment by mightydanp** [comment]
Whenever i used a character save file from online and it broke my rank. I had to delete the profile.sav and it got ride of all my keys

**Comment by apocalyptech** [comment]
Ah, okay, I suppose they must be in there somewhere then.  Well, if you're willing to take the time to look through the JSON yourself, definitely let me know if you find 'em.  I'll take a look at some point as well, though I admit that Golden Key editing is pretty low on my priority list.  It'd get moved along if you were able to point me right at 'em.  :)

**Comment by mightydanp** [comment]
How do i find it ?

**Comment by apocalyptech** [comment]
https://github.com/apocalyptech/bl3-cli-saveedit/blob/master/README-profile.md#output-formats

Or specifically the line:

    bl3-profile-edit profile.sav profile.json -o json

Which will leave you with a file named `profile.json`.  JSON files are just text files, so you can edit it in basically any text editor.  There's probably JSON-specific editors out there as well which would let you expand/collapse areas at will, if you want.

**Comment by apocalyptech** [comment]
FYI, I *did* end up looking into this briefly earlier today, 'cause I'd been hopping between Steam+Epic versions and ended up noticing it while looking at some JSON diffs.  Specifically, golden keys use the `bank_inventory_category_list` attribute.  For instance in my current profile:

  "bank_inventory_category_list": [
    {
      "base_category_definition_hash": 4031389239,
      "quantity": 146
    }
  ],

The `4031389239` is a hash of the string `/Game/Gear/_Shared/_Design/InventoryCategories/InventoryCategory_GoldenKey.InventoryCategory_GoldenKey`, using the same algorithm used to hash the weapon skins/trinkets for those lookups.

So, I may end up adding a golden key set in here in a bit, after all.

**Comment by apocalyptech** [comment]
Okay, yeah, easy enough once I saw how to do it.  This'll be in 1.6.0, which'll probably be released tomorrow after the new Takedown gets released and I have the time to update with new items, etc.
