### ISSUE TITLE
DLC4 update also added lost loot machine SDU upgrades to profile

### ISSUE THREAD

**Issue by ensiform** [apocalyptech/bl3-cli-saveedit#13]
I don't know the exact amounts haven't played yet but this change was listed on the Borderlands news page iirc. 

Just FYI! Thanks for all your hard work.

**Comment by apocalyptech** [comment]
Yep, that should already be in there (in addition to the other SDU upgrades).  Looked like it was working for me, but let me know if it doesn't unlock it properly for you.  :)

Thx for the report!

**Comment by ensiform** [comment]
I missed the changes in fc15b708488a0a11e10db3a56eb02ac764fbb21c when skimming on my phone. I see it now :+1:

**Comment by apocalyptech** [comment]
No worries!  I'd rather have an easy-to-close bugreport than miss it.  :)  Thanks again!
