### ISSUE TITLE
it doesn't recognise any command that starts with bl3 and i did everything right 

### ISSUE THREAD

**Issue by TheGodOfNoodles** [apocalyptech/bl3-cli-saveedit#16]

**Comment by apocalyptech** [comment]
Hello!  Could you provide a screenshot of your terminal/cmd/powershell whatever when you attempt to run one of the commands?  Also maybe screenshot what happens when you run a `pip3 install bl3-cli-saveedit` (or `pip install bl3-cli-saveedit`, if that's what works on your system) again?

**Comment by TheGodOfNoodles** [comment]
wo ur quick

**Comment by TheGodOfNoodles** [comment]
it says that its not installed on the right path? how do i fix that

**Comment by apocalyptech** [comment]
Without screenshots I probably won't be able to help out much.  Make sure that you're able to at least get a response back from running `python`, as per the docs, though:

https://github.com/apocalyptech/bl3-cli-saveedit#notes-for-people-using-windows

**Comment by TheGodOfNoodles** [comment]
im sorry im verry new to all of this il try doing that

**Comment by TheGodOfNoodles** [comment]
does it need to be that exact specific version of python?

**Comment by apocalyptech** [comment]
No, just whatever's latest in the 3.x line should be fine.  3.9.2 is the most recent, I think.

**Comment by TheGodOfNoodles** [comment]
ty i made it in a custom instilation and enabled path and its working ty :)

**Comment by apocalyptech** [comment]
Cool, glad you got it working!  Have a good one.
