### ISSUE TITLE
Inventory slots

### ISSUE THREAD

**Issue by Revadike** [apocalyptech/bl3-cli-saveedit#17]
Is there a way to permanently unlock 200 (or more) inventory slots, just like I can do with a trainer (not permanent).

**Comment by apocalyptech** [comment]
Heya -- not with save editing, anyway.  I suspect that you could probably add however many items to inventory that you want, but the "overflowed" item slots wouldn't be usable after selling/dropping the items.

I believe that expanded inventory slots could be done with hotfix modding, though.  I don't think anyone's actually done a mod to do it yet, though you could take a look: https://github.com/BLCM/bl3mods/wiki - if you wanted to try your hand at doing a mod yourself, there's some resources about it here: https://github.com/BLCM/BLCMods/wiki/Borderlands-3-Modding-Info
