### ISSUE TITLE
Wonderlands fork

### ISSUE THREAD

**Issue by ensiform** [apocalyptech/bl3-cli-saveedit#24]
Are you planning on supporting wonderlands when that comes out? I'm guessing since it's BL3 engine based the saves won't be that difficult to figure out the differences.

**Comment by apocalyptech** [comment]
Heya!  Yes, though with caveats:

1. I'm actually pretty clueless when it comes to extracting encryption "keys" and CRC magic numbers and the like.  I'm generally at the mercy of smartypants folks like Gibbed to provide that kind of info.  So I'll probably be waiting for someone cleverer than myself to provide those.
2. I'm still undecided as to whether I'm gonna wait for the Steam release for the game, so I might not even have the game for another six months (or whenever).

So, we'll see!  The editor's opensource, at least, so even if I don't pick up Wonderlands for awhile, someone else could fork it and do it themselves.  :)

**Comment by apocalyptech** [comment]
Oh, btw -- in the end I decided to just wait for the Steam release.  So the earliest you'll see anything forthcoming from myself is ~6months or whenever.  I expect this'll need relatively minor updates to support Wonderlands, though, so if anyone feels like forking, hopefully it shouldn't be bad.

**Comment by ensiform** [comment]
I was already playing on Linux last night, runs really good with EGS already. Smoother than BL3 even. Also noticed gibbed started too.

**Comment by ensiform** [comment]
FWIW gibbed has started some work it seems?

https://github.com/gibbed/WonderlandsProtos
https://github.com/gibbed/WonderlandsDumps

**Comment by apocalyptech** [comment]
Indeed, though I expect that'll probably be all he does with it, if past history with BL3 is anything to go by.  In the meantime, someone *did* fork this repo for Wonderlands, though I believe only JSON export/import is supported: https://github.com/DataCluster0/wonderlands-cli-saveedit

It looks like there's a fork of FromDarkHell's GUI editor as well, so some options are popping up in the meantime: https://github.com/jokarwent/BL3SaveEditor/tree/wonderlands
