### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by KrisVish** [apocalyptech/bl3-cli-saveedit#28]
Hi  Apocalyptech

we are using bl3 command line save editor
we are using bl3-save-edit 1bkpymallweapanoints.sav 1apo2.sav  --import-items  new.txt

The problem we are facing is instead of copying items from text file,  bl3-save-edit  also copies mission data,  challenge data and  even character name/class  from old save file to new save file

my grand daughter only needs items to be copied leaving the rest untouched

Thank You
Kris

**Comment by abramhindle** [comment]
import-items just imports items into a savefile. All the state of the original savefile, including the mission data is maintained. You need to start a new game or TVHM to "reset" the missions. Or remove individual missions.

**Comment by KrisVish** [comment]
Hi Apocalyptech

Please remember my grand daughter has made 60% progress on new amara save file and cannot affordto loose progress by starting a new game or tvhm reset missions

we used amara save as new save file and zane as old save file

After cli-editor completed successfully,  she loaded bl3 with amara save and amara had been replaced by zane in main menu and ingame and amara mission progress had been lost

zane had replaced amara in every screen

Please refer to log
bl3-save-edit 1bkpymallweapanoints.sav 1apo.sav -i new.txt --allow-fabricator
WARNING: 1apo.sav already exists.  Overwrite [y/N]? y

Loading 1bkpymallweapanoints.sav

Making requested changes...

 - Importing items from new.txt
   + Hellwalker (level 72)
   + Blue Vladof AR (level 72)
   + Purple Artifact (level 72)

Wrote savegame to 1apo.sav

Please help us

Thank You
Kris

**Comment by apocalyptech** [comment]
Hello -- The item-import function *won't* transfer any character or mission info.  All it does is import weapons.  Are you sure that `1bkpymallweapanoints.sav` was your granddaughter's Amara save file?  The command you posted would take `1bkpymallweapanoints.sav`, add in those three items (Hellwalker, Vladof AR, Artifact), and save it out as `1apo.sav`.  The first savegame in the list is the "base" that gets added onto.

**Comment by KrisVish** [comment]
Hi Apocalyptech

Thank You for your advise

we could not understand to which save items will get added

we will try again

Thank You Again
Kris

**Comment by KrisVish** [comment]
Hi Apocalyptech

My grand daughter has a problem using standalone third person hotfix mod

She need to adjust camera distance from character because of her medical problem

But we do not know how x, y, z positive and negative values change camera position forward / backward,  higher / lower and right / left  from character

Please let us know

Thank You
Kris

**Comment by apocalyptech** [comment]
> But we do not know how x, y, z positive and negative values change camera position forward / backward, higher / lower and right / left from character

Sorry, I've got no experience with the third-person mod!  The Z axis should be up/down, though, and I believe negative is generally lower.

**Comment by KrisVish** [comment]
Hi Apocalyptech

Thank You for all  help  again

Kris
