### ISSUE TITLE
Output file location?

### ISSUE THREAD

**Issue by BitTiamatu** [apocalyptech/bl3-cli-saveedit#6]
Where does the new file save to?

When I run the command and arguments there is no saved file with the new name I have given it in the current directory. If I run it again there is a prompt to overwrite so it is saving somewhere.

**Comment by ensiform** [comment]
I usually do 4.sav 4.sav followed by the rest of parameters. With a backup already made prior

**Comment by BitTiamatu** [comment]
Tried that also. It just keeps telling me that nothing is being done since it already has done it.

**Comment by BitTiamatu** [comment]
Found the problem. Antivirus was sandboxing to a virtual hard drive. Please disregard.

**Comment by apocalyptech** [comment]
Ah, cool, glad you figured it out!  Have a good one!
