### ISSUE TITLE
Missing vehicle chassis `WT_Horse_Biobeast`

### ISSUE THREAD

**Issue by sandsmark** [apocalyptech/bl3-cli-saveedit#7]
I just copied in my latest save (I've been testing with a pretty old one), and bl3save.cli_info has started failing with:

key = chassis_to_vehicle[v.asset_path]
KeyError: '/Geranium/Vehicles/Horse/Design/WT_Horse_Biobeast.WT_Horse_Biobeast'

When trying to list unlocked vehicle parts.

**Comment by sandsmark** [comment]
Ok, I think there's more stuff going on. For some reason bl3-cli-saveedit is not able to read out any of the inventory anymore, though [my own re-implementation](https://github.com/sandsmark/borderlands3-save-editor/blob/master/src/Savegame.cpp) (doing basically the exact same) is able to read it out:

![image](https://user-images.githubusercontent.com/25765/80311553-ccab9b80-87cf-11ea-87ff-ab55dae38507.png)

**Comment by ensiform** [comment]
Did you upgrade to latest version? https://github.com/apocalyptech/bl3-cli-saveedit/commit/fdfbf30d4e144727eceabda049f7c0928bce6243

**Comment by apocalyptech** [comment]
You just need to update to 1.4.0 -- there was a new `InventorySerialNumberDatabase.dat` file, and saves since last Thursday are saved with a new version.  1.4.0 updated with that, so it should be good to go.

**Comment by apocalyptech** [comment]
I suppose I'll go ahead and close this out; let me know if 1.4.0 continues to be problematic, though!

**Comment by sandsmark** [comment]
I was sure I had git pulled, but I was sitting in the wrong terminal window and hadn't on both machines.. Sorry for the noise. :-)

**Comment by apocalyptech** [comment]
No worries!  :)
